export const CATEGORIES = [
  'Home 🏠',
  'Transportation 🚗',
  'Groceries 🛒',
  'Health 🏥',
  'Entertainment 🎭',
  'Travel ✈️',
  'Subscriptions 💳',
  'Shopping 🛍️',
  'Education 📚',
  'Gifts 🎁',
  'Debt 🏦',
  'Leisure 🍸',
  'Other ❓',
];